# 배열의 형태(shape) 변경
- 형태 변경 시 원소의 개수는 불변

## reshape()을 이용한 차원 변경
- `numpy.reshape(a, newshape)` 또는 `ndarray.reshape(newshape)`
    - a: 형태를 변경할 배열
    - newshape : 변경할 형태 설정
        - 원소의 개수를 유지하는 shape으로만 변환 가능
        - 기존 배열의 size와 새로 생성 할 배열의 size가 다를 경우 Exception발생

In [1]:
import numpy as np

In [2]:
# Vector
a = np.arange(20)
print(a.shape)
print(a.size)

(20,)
20


In [3]:
# Matrix로 변환
a2 = np.reshape(a, (4, 5))
print(a2.shape)
print(a2.size)
a2

(4, 5)
20


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [4]:
# Tensor로 변환
a3 = np.reshape(a, (2, 2, 5))
print(a3.shape)
print(a3.size)
a3

(2, 2, 5)
20


array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [5]:
# 다른 방법
a4 = a.reshape((2, 2, 5)) # np가 아닌 a에 바로 reshape
a5 = a.reshape(4, 5) # 튜플로 묶지 안고 shape 설정
print(a4.shape, a4.size)
print(a5.shape, a5.size)

(2, 2, 5) 20
(4, 5) 20


In [6]:
# 축 지정 시 하나의 축의 size를 -1로 지정 가능 : -1 지정 시 나머지 size를 그 축의 size로 지정
a6 = a.reshape(2, 2, -1)
print(a6.shape, a6.size)

(2, 2, 5) 20


In [7]:
# Tensor -> Vector
a7 = a6.reshape(20)
print(a7.shape, a7.size)

(20,) 20


## 차원 늘리기(확장)
- dummy 축을 확장
    - size가 1인 축(axis)

### numpy.newaxis 속성을 이용해 차원 늘리기
- size가 1인 rank를 늘릴때 사용 
    - 지정한 axis에 size 1인 축을 추가
- slicing에 사용하거나 indexing에 `...`과 같이 사용
    - slicing의 경우 원하는 위치의 축 연장 가능
    - index에 ...과 사용하는 경우 첫번째나 마지막 축 연장 시 사용

In [8]:
b = np.arange(1, 6)
print(b.shape)
b

(5,)


array([1, 2, 3, 4, 5])

In [9]:
# newaxis와 slicing 연산자를 이용해 늘리기
b2 = b[:, np.newaxis]
print(b2.shape)
b2

(5, 1)


array([[1],
       [2],
       [3],
       [4],
       [5]])

In [10]:
b3 = b[np.newaxis, :]
print(b3.shape)
b3

(1, 5)


array([[1, 2, 3, 4, 5]])

In [11]:
b4 = np.arange(20).reshape(2, 2, 5)
print(b4.shape)
b4

(2, 2, 5)


array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [12]:
# [:] : 축 별 순서대로 지정
# (2, 2, 5) -> (1, 2, 2, 5)
b5 = b4[np.newaxis, :, :, :]
b5.shape

(1, 2, 2, 5)

In [13]:
# (2, 2, 5) -> (2, 1, 2, 5)
b6 = b4[:, np.newaxis, :, :]
b6.shape

(2, 1, 2, 5)

### indexing에 ... 과 같이 사용
- ndarray[..., np.newaxis]
- 첫번째 축이나 마지막 축을 늘릴때만 사용가능

In [14]:
b4.shape

(2, 2, 5)

In [15]:
# 앞에 더미축 추가
b7 = b4[np.newaxis, ...]
b7.shape

(1, 2, 2, 5)

In [16]:
# 뒤에 더미축 추가
b8 = b4[..., np.newaxis]
b8.shape

(2, 2, 5, 1)

### numpy.expand_dims (배열, axis)
- 매개변수로 받은 배열에 지정한 axis의 rank를 확장

In [17]:
b4.shape

(2, 2, 5)

In [18]:
# 앞에 추가
b9 = np.expand_dims(b4, axis=0)
b9.shape

(1, 2, 2, 5)

In [19]:
# 중간에 추가
b10 = np.expand_dims(b4, axis=1)
b10.shape

(2, 1, 2, 5)

In [20]:
# 마지막에 추가
b11 = np.expand_dims(b4, axis=-1) # axis=-1 : 뒤에서 첫번째 축
b11.shape

(2, 2, 5, 1)

## 차원 줄이기(축소)

### numpy.squeeze(배열, axis=None), 배열객체.squeeze(axis=None)
- 배열에서 지정한 축(axis)을 제거하여 차원(rank) 축소
- 제거하려는 축의 size는 1이어야 함
- 축을 지정하지 않으면 size가 1인 모든 축을 제거
    - (3,1,1,2) => (3,2)
- 더미 축이 아닌 축 제거 시 Exception 발생

In [21]:
b11.shape

(2, 2, 5, 1)

In [22]:
c = b11.squeeze()
c.shape

(2, 2, 5)

In [23]:
d = np.arange(20).reshape(1, 2, 1, 2, 1, 5, 1)
d.shape

(1, 2, 1, 2, 1, 5, 1)

In [24]:
# 0축 제거
d2 = d.squeeze(axis=0)
d2.shape

(2, 1, 2, 1, 5, 1)

In [25]:
# 2축 제거
d3 = d.squeeze(axis=2)
d3.shape

(1, 2, 2, 1, 5, 1)

In [26]:
# 축 미지정 시 모든 더미 축 제거
d4 = d.squeeze()
d4.shape

(2, 2, 5)

### 배열객체.flatten()
- 다차원 배열을 1차원으로 변환

In [27]:
print(d4.shape)
d5 = d4.flatten()
print(d5.shape)
d5

(2, 2, 5)
(20,)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

## numpy.append(), numpy.insert(), numpy.delete()
- ### append(배열, 추가할값, axis=None)
    - 배열의 마지막 index에 추가할값을 추가
    - axis : 축 지정
        - None(기본값) : flatten 한 후 추가
- ### insert(배열, index, 추가할값, axis=None)
    - 배열의 index에 추가할값을 추가
    - axis : 축 지정
        - None(기본값) : flatten 한 후 삽입
- ### delete(배열, 삭제할index, axis=None)  
    - 배열의 삭제할index의 값들을 삭제
    - 삭제할 index는 index 또는 slice
    - axis : 축 지정
        - None(기본값) : flatten 한 후 삭제
        
- 원본은 불변

### append()

#### 1차원

In [28]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
# 맨뒤에 추가
np.append(a, 100)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9, 100])

In [30]:
# 다수의 값 추가
np.append(a, [200, 300, 400])

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9, 200, 300, 400])

In [31]:
# 원본은 불변
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 다차원

In [32]:
a2 = np.arange(12).reshape(4, 3)
print(a2.shape)
a2

(4, 3)


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [33]:
# 축 미지정 시 flatten(1차원으로 변환) 후 처리
np.append(a2, 100)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11, 100])

In [34]:
# 추가 값은 지정한 축의 값과 같은 shape로 추가
np.append(a2, 
          [
              [100, 200, 300],
              [1000, 2000, 3000]
          ],
          axis=0)

array([[   0,    1,    2],
       [   3,    4,    5],
       [   6,    7,    8],
       [   9,   10,   11],
       [ 100,  200,  300],
       [1000, 2000, 3000]])

In [35]:
np.append(a2, 
          [[11], [22], [33], [44]],
          axis=1)

array([[ 0,  1,  2, 11],
       [ 3,  4,  5, 22],
       [ 6,  7,  8, 33],
       [ 9, 10, 11, 44]])

In [36]:
np.append(a2, 
          [[11, 111, 1111], [22, 222, 2222], [33, 333, 3333], [44, 444, 4444]],
          axis=1)

array([[   0,    1,    2,   11,  111, 1111],
       [   3,    4,    5,   22,  222, 2222],
       [   6,    7,    8,   33,  333, 3333],
       [   9,   10,   11,   44,  444, 4444]])

### insert

#### 1차원

In [37]:
print(a.shape)
a

(10,)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
# insert(배열, index, 값)
np.insert(a, 1, 100)

array([  0, 100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [39]:
# 하나의 index에 다수의 값 추가
np.insert(a, 0, [100, 200, 300])

array([100, 200, 300,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [40]:
# 다수의 index에 값 추가
np.insert(a, [0, 2], [100, 200])

array([100,   0,   1, 200,   2,   3,   4,   5,   6,   7,   8,   9])

#### 다차원

In [41]:
print(a2.shape)
a2

(4, 3)


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [42]:
# 축 미지정 시 flatten(1차원으로 변환) 후 처리
np.insert(a2, 2, 1000)

array([   0,    1, 1000,    2,    3,    4,    5,    6,    7,    8,    9,
         10,   11])

In [43]:
# 축 지정
np.insert(a2, 2, [[10, 20, 30], [100, 200, 300]], axis=0)

array([[  0,   1,   2],
       [  3,   4,   5],
       [ 10,  20,  30],
       [100, 200, 300],
       [  6,   7,   8],
       [  9,  10,  11]])

In [44]:
# 축 지정
np.insert(a2, 2, [[1], [2], [3], [4]], axis=1) #[[inser할 데이터셋]]

array([[ 0,  1,  1,  2,  3,  4,  2],
       [ 3,  4,  1,  2,  3,  4,  5],
       [ 6,  7,  1,  2,  3,  4,  8],
       [ 9, 10,  1,  2,  3,  4, 11]])

In [45]:
# 축 별 다수의 값 삽입
np.insert(a2, 2, [[1, 2, 3, 4], [100, 200, 300, 400]], axis=1)

array([[  0,   1,   1, 100,   2],
       [  3,   4,   2, 200,   5],
       [  6,   7,   3, 300,   8],
       [  9,  10,   4, 400,  11]])

In [46]:
# 축 별 다수의 값 삽입
np.insert(a2, [1, 2], [[100,200],
                       [300,400],
                       [500,600],
                       [700,800]], axis=1)

array([[  0, 100,   1, 200,   2],
       [  3, 300,   4, 400,   5],
       [  6, 500,   7, 600,   8],
       [  9, 700,  10, 800,  11]])

### delete

#### 1차원

In [47]:
print(a.shape)
a

(10,)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
# delete(배열, index)
np.delete(a, 0)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
# 다수 index 삭제
np.delete(a, [0, 4, 7])

array([1, 2, 3, 5, 6, 8, 9])

In [50]:
# slicing을 통한 삭제
# slicing[::] => 배열 값 조회 => 조회된 값으로 index번호로 인식하여 삭제 => 사용불가
# np.s_[:::] : slicing 문법 객체 생성 
np.delete(a, np.s_[2:6])

array([0, 1, 6, 7, 8, 9])

#### 다차원

In [51]:
print(a2.shape)
a2

(4, 3)


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [52]:
# 축 미지정 시 flatten(1차원으로 변환) 후 처리
np.delete(a2, 2)

array([ 0,  1,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [53]:
# 축지정
np.delete(a2, 1, axis=0)

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [54]:
# 축지정
np.delete(a2, 1, axis=1)

array([[ 0,  2],
       [ 3,  5],
       [ 6,  8],
       [ 9, 11]])

In [55]:
# slicing을 통한 삭제
np.delete(a2, np.s_[:2], axis=1)

array([[ 2],
       [ 5],
       [ 8],
       [11]])

## 배열 합치기
- ### np.concatenate(합칠 배열리스트, axis=0)
    - 여러 배열을 **축의개수(rank)**를 유지하며 결합
    - axis 파라미터 : 축지정
        - 지정된 축을 기준으로 결합 
        - default : 0
    - 합치는 배열의 축의 개수(rank, 차원)는 동일해야 함
    - axis속성으로 지정한 축 이외의 축의 크기가 동일해야 함
    - 결과의 축의개수(rank)는 대상 배열의 rank와 동일
        - 1차원끼리 합치면 1차원결과가 나옴
- ### 합칠 대상 배열의 rank가 2일 경우(행렬) 
    - vstack()
    - hstack()
    - np.concatenate()의 간단버전
- ### vstack(합칠배열리스트)
    - 수직으로 쌓는다.
    - concatenate() 의 axis=0 와 동일
    - 합칠 배열들의 열수가 동일해야 함
- ### hstack(합칠배열리스트)
    - 수평으로 쌓는다.
    - concatenate() 의 axis=1 와 동일
    - 합칠 배열들의 행 수가 동일해야 함

### concatenate()

- axis=0 이면 0이 늘어난다. 0을 기준으로 합치므로 (그래서 밑으로 (행이 늘어남) 붙음)
    - 그래서 각 배열의 컬럼 수가 동일해야함
- axis=1 이면 1이 늘어난다. 1을 기준으로 합치므로 (그래서 옆으로 (컬럼이 늘어남) 붙음)
    - 그래서 각 배열의 행수가 동일해야 함

#### 1차원

In [56]:
a = np.arange(10)
b = np.arange(100, 110)
c = np.arange(1000, 1010)
print(a.shape, b.shape, c.shape)

(10,) (10,) (10,)


In [57]:
# 1차원 배열 틀 -> axis=0 -> 합치는 기준 : 0
r = np.concatenate([a, b, c])
print(r.shape)
r

(30,)


array([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,  100,
        101,  102,  103,  104,  105,  106,  107,  108,  109, 1000, 1001,
       1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009])

#### 다차원

In [58]:
a = np.arange(12).reshape(4, 3)
b = np.arange(100, 112).reshape(4, 3)
c = np.arange(6).reshape(2,3)
d = np.arange(3*5*5).reshape(3, 5, 5)
e = np.arange(100, 175).reshape(3, 5, 5)
print(a.shape, b.shape, c.shape, d.shape, e.shape)

(4, 3) (4, 3) (2, 3) (3, 5, 5) (3, 5, 5)


In [59]:
# 2차원 배열 -> axis : 0, 1
r = np.concatenate([a, b]) # default : axis=0
print(r.shape)
r

(8, 3)


array([[  0,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8],
       [  9,  10,  11],
       [100, 101, 102],
       [103, 104, 105],
       [106, 107, 108],
       [109, 110, 111]])

In [60]:
# 2차원 배열 -> axis : 0, 1
r = np.concatenate([b, a], axis=1)
print(r.shape)
r

(4, 6)


array([[100, 101, 102,   0,   1,   2],
       [103, 104, 105,   3,   4,   5],
       [106, 107, 108,   6,   7,   8],
       [109, 110, 111,   9,  10,  11]])

In [61]:
# 합치는 기준축을 제외한 나머지 축의 size는 동일해야함
# a(4, 3)와 c(2, 3) 병합
r = np.concatenate([a, c], axis=0) # axis=1 경우 나머지 축의 size가 달라 Error 발생
print(r.shape)
r

(6, 3)


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [ 0,  1,  2],
       [ 3,  4,  5]])

In [62]:
#3차원 axis : 0
r = np.concatenate([d, e], axis=0)
print(r.shape)
r

(6, 5, 5)


array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24]],

       [[ 25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49]],

       [[ 50,  51,  52,  53,  54],
        [ 55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74]],

       [[100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114],
        [115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124]],

       [[125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134],
        [135, 136, 137, 138, 139],
        [140, 141, 142, 143, 144],
        [145, 146, 147, 148, 149]],

       [[150, 151, 152, 153, 154],
        [155, 156, 157, 158, 159],
        [160, 161, 162, 163, 164],
        [1

In [63]:
# 3차원 axis : 1
r = np.concatenate([d, e], axis=1)
print(r.shape)
r

(3, 10, 5)


array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24],
        [100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114],
        [115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124]],

       [[ 25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49],
        [125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134],
        [135, 136, 137, 138, 139],
        [140, 141, 142, 143, 144],
        [145, 146, 147, 148, 149]],

       [[ 50,  51,  52,  53,  54],
        [ 55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74],
        [150, 151, 152, 153, 154],
        [155, 156, 157, 158, 159],
        [160, 161, 162, 163, 164],
        [165, 16

In [64]:
# 3차원 axis : 2
r = np.concatenate([d, e], axis=2)
print(r.shape)
r

(3, 5, 10)


array([[[  0,   1,   2,   3,   4, 100, 101, 102, 103, 104],
        [  5,   6,   7,   8,   9, 105, 106, 107, 108, 109],
        [ 10,  11,  12,  13,  14, 110, 111, 112, 113, 114],
        [ 15,  16,  17,  18,  19, 115, 116, 117, 118, 119],
        [ 20,  21,  22,  23,  24, 120, 121, 122, 123, 124]],

       [[ 25,  26,  27,  28,  29, 125, 126, 127, 128, 129],
        [ 30,  31,  32,  33,  34, 130, 131, 132, 133, 134],
        [ 35,  36,  37,  38,  39, 135, 136, 137, 138, 139],
        [ 40,  41,  42,  43,  44, 140, 141, 142, 143, 144],
        [ 45,  46,  47,  48,  49, 145, 146, 147, 148, 149]],

       [[ 50,  51,  52,  53,  54, 150, 151, 152, 153, 154],
        [ 55,  56,  57,  58,  59, 155, 156, 157, 158, 159],
        [ 60,  61,  62,  63,  64, 160, 161, 162, 163, 164],
        [ 65,  66,  67,  68,  69, 165, 166, 167, 168, 169],
        [ 70,  71,  72,  73,  74, 170, 171, 172, 173, 174]]])

### vstack()
- 아래에 붙이는 개념이므로 열수가 맞아야 한다. 
- axis=0과 동일

In [65]:
a.shape, b.shape

((4, 3), (4, 3))

In [66]:
r = np.vstack([a, b])
print(r.shape)
r

(8, 3)


array([[  0,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8],
       [  9,  10,  11],
       [100, 101, 102],
       [103, 104, 105],
       [106, 107, 108],
       [109, 110, 111]])

### hstack()
- 옆으로 붙이는 것이므로 행 수가 동일해야 함
- axis=1과 동일

In [67]:
a.shape, b.shape

((4, 3), (4, 3))

In [68]:
r = np.hstack([a, b])
print(r.shape)
r

(4, 6)


array([[  0,   1,   2, 100, 101, 102],
       [  3,   4,   5, 103, 104, 105],
       [  6,   7,   8, 106, 107, 108],
       [  9,  10,  11, 109, 110, 111]])

## 배열 분할 하기
- ### split(배열, 분할기준, axis)
    - 지정한 축을 기준으로 배열을 분할
    - 반환값: 분할한 narray를 가진 리스트로 리턴
    - 배열: 분할할 배열
    - 분할기준
        - 정수 : 지정 개수만큼 분할
        - 리스트 : 분할 기준 index들
    - axis(축)
        - 분할할 기준 축을 지정한다. axis = 0 (기본) 
        - 2D의 경우 axis=0: 행 기준 분할, axis=1: 열 기준 분할
- ### vsplit(배열, 분할기준)
    - 행 기준 분할
    - split()의 axis=0과 동일
    - 분할기준
        - 정수 : 지정 개수만큼 분할
        - 리스트 : 분할 기준 index들
- ### hsplit(배열, 분할기준)
    - 열 기준 분할
    - split()의 axis=1과 동일
    - 분할기준
        - 정수 : 지정 개수만큼 분할
        - 리스트 : 분할 기준 index들
- **주의:** 분할기준을 정수(개수)로 할 경우 분할후 원소수가 동일해야 함 

#### 1차원

In [69]:
a = np.arange(10)
a.shape

(10,)

In [70]:
# 동일한 size의 배열로 분할
r = np.split(a, 2)
print(type(r)) # 나눈 배열을 리스트에 묶어 반환
r

<class 'list'>


[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [71]:
r1, r2 = np.split(a, 2)
print(r1.shape, r2.shape)
print(a)
print(r1)
print(r2)

(5,) (5,)
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]
[5 6 7 8 9]


In [72]:
# size가 다르게 설정할 경우 : index를 지정하여 그 앞에서 분할
r1, r2, r3 = np.split(a, [3,7])
print(r1.shape, r2.shape, r3.shape)
print(r1)
print(r2)
print(r3)

(3,) (4,) (3,)
[0 1 2]
[3 4 5 6]
[7 8 9]


#### 다차원

In [73]:
b = np.arange(42).reshape(6,7)
print(b.shape)
b

(6, 7)


array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41]])

In [74]:
# axix=0 분할
r1, r2 = np.split(b, 2)
print(r1.shape, r2.shape)
print(r1)
print('-' * 15)
print(r2)

(3, 7) (3, 7)
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]
---------------
[[21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]]


In [75]:
# axis=1 분할 : 분할 시 size가 달라 바로 나눌 수 없음 => index기준으로 분할
r1, r2 = np.split(b, [3], axis=1)
print(r1.shape, r2.shape)
print(r1)
print('-' * 15)
print(r2)

(6, 3) (6, 4)
[[ 0  1  2]
 [ 7  8  9]
 [14 15 16]
 [21 22 23]
 [28 29 30]
 [35 36 37]]
---------------
[[ 3  4  5  6]
 [10 11 12 13]
 [17 18 19 20]
 [24 25 26 27]
 [31 32 33 34]
 [38 39 40 41]]


## hsplit()/vsplit()
- 2차원 배열을 분할

In [76]:
# hsplit
r1, r2, r3 = np.hsplit(b, [3, 5]) # axis=1
print(r1.shape, r2.shape, r3.shape)
print(r1)
print('-' * 15)
print(r2)
print('-' * 15)
print(r3)

(6, 3) (6, 2) (6, 2)
[[ 0  1  2]
 [ 7  8  9]
 [14 15 16]
 [21 22 23]
 [28 29 30]
 [35 36 37]]
---------------
[[ 3  4]
 [10 11]
 [17 18]
 [24 25]
 [31 32]
 [38 39]]
---------------
[[ 5  6]
 [12 13]
 [19 20]
 [26 27]
 [33 34]
 [40 41]]


In [77]:
# vsplit
r1, r2, r3 = np.vsplit(b, [3, 5]) # axis=0
print(r1.shape, r2.shape, r3.shape)
print(r1)
print('-' * 15)
print(r2)
print('-' * 15)
print(r3)

(3, 7) (2, 7) (1, 7)
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]
---------------
[[21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]
---------------
[[35 36 37 38 39 40 41]]
