# 배열을 파일에 저장 및 불러오기
- ## 바이너리 파일로 저장/불러오기
    - ### np.save("파일경로", 배열)
        - 배열을 raw 바이너리 형식으로 저장 (압축하지 않은)
        - 파일명에 확장자로 npy를 붙임 (무조건 붙임 abc.xxx 해도 abc.xxx.npy 로 저장)
    - ### np.load("파일경로") 
        - 파일에 저장된 배열을 불러오기
    - ### np.savez("파일경로", 이름=배열, 이름=배열, ...)
        - 여러개의 배열을 저장할 때 사용
        - 파일명에 확장자로 npz가 붙음
        - 내부적으로 압축해서 저장
        - load() 함수로 불러오면 저장된 배열목록이 반환 된다. 저장시 지정한 이름을 이용해 조회 
- ## 텍스트 파일로 저장하고 불러오기
    - ### savetxt("파일경로", 배열 [, delimiter='공백') 
        - 텍스트 형태로 저장
        - 각 원소는 공백을 기준으로 나뉘며 delimiter 속성으로 구분자를 지정가능 (delimiter생략시 공백)
        - 1차원과 2차원 배열만 저장 가능 (3차원 이상은 저장 불가)
    - ### loadtxt("파일경로" [,dtype=float, delimiter=공백)

In [1]:
import numpy as np

In [2]:
a = np.array([1, 5, 8, 9, 10]) # 1차원
b = np.random.normal(size=(5,10)) # 2차원
c = np.ones(shape=(3, 4, 2)) # 3차원 
print(a.shape, b.shape, c.shape)

(5,) (5, 10) (3, 4, 2)


In [3]:
# 저장 - binary 형식
import os
# 저장할 디렉토리가 없는 경우 새로 생성
save_dir = 'save_data'
if not os.path.isdir(save_dir): # 디렉토리 유무확인
    os.mkdir(save_dir) # 디렉토리 생성
    
np.save('save_data/a', a) # a배열을 save_data/a.npy로 저장
np.save('save_data/b', b) # b배열을 save_data/b.npy로 저장
np.save('save_data/c', c) # c배열을 save_data/c.npy로 저장

In [4]:
# binary 저장된 배열 불러오기
a2 = np.load('save_data/a.npy')
b2 = np.load('save_data/b.npy')
c2 = np.load('save_data/c.npy')
print(a2)
print('-' * 20)
print(b2)
print('-' * 20)
print(c2)

[ 1  5  8  9 10]
--------------------
[[-0.66280568 -0.47096807  0.22561768 -1.04617192  0.7383947  -1.03382219
   0.35677394 -0.21659241 -0.70515617 -0.30316389]
 [ 0.94634794  1.08653257  0.5871669  -0.08584565 -0.4219474   0.45693989
  -0.45819309 -0.86610361 -0.90128871 -1.36280905]
 [-0.79376331  0.04986632 -0.07642652  0.53623186  0.81505118  0.73838202
  -0.2489301  -0.28261793  0.79485771 -0.87212444]
 [-0.12152128 -1.26836659 -0.92585965 -1.20309212  0.96513725  1.22387413
  -0.11198889 -1.17087882  1.00641888 -0.22424133]
 [-0.29038945  0.20921193  1.47712692  0.30394688 -1.07743073 -0.51711237
   1.35619319  1.57105273  1.12669418 -0.08767327]]
--------------------
[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


In [5]:
# 다수의 배열을 한 파일에 저장
np.savez('save_data/all', arr_a=a, arr_b=b, arr_c=c)

In [6]:
# npz 파일 읽어오기
arr_all = np.load('save_data/all.npz')

In [7]:
# 저장 시 저정 이름 조회
arr_all.files

['arr_a', 'arr_b', 'arr_c']

In [8]:
a3 = arr_all['arr_a']
b3 = arr_all['arr_b']
c3 = arr_all['arr_c']
print(a3)
print('-' * 20)
print(b3)
print('-' * 20)
print(c3)

[ 1  5  8  9 10]
--------------------
[[-0.66280568 -0.47096807  0.22561768 -1.04617192  0.7383947  -1.03382219
   0.35677394 -0.21659241 -0.70515617 -0.30316389]
 [ 0.94634794  1.08653257  0.5871669  -0.08584565 -0.4219474   0.45693989
  -0.45819309 -0.86610361 -0.90128871 -1.36280905]
 [-0.79376331  0.04986632 -0.07642652  0.53623186  0.81505118  0.73838202
  -0.2489301  -0.28261793  0.79485771 -0.87212444]
 [-0.12152128 -1.26836659 -0.92585965 -1.20309212  0.96513725  1.22387413
  -0.11198889 -1.17087882  1.00641888 -0.22424133]
 [-0.29038945  0.20921193  1.47712692  0.30394688 -1.07743073 -0.51711237
   1.35619319  1.57105273  1.12669418 -0.08767327]]
--------------------
[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


In [9]:
# 텍스트 파일로 저장 (1차원, 2차원 배열만 가능)
np.savetxt('save_data/a_txt.csv', a, delimiter=',')
np.savetxt('save_data/b_txt.csv', b, delimiter=',')

In [10]:
# 저장된 텍스트 파일 불러오기
a4 = np.loadtxt('save_data/a_txt.csv', delimiter=',')
b4 = np.loadtxt('save_data/b_txt.csv', dtype=float, delimiter=',')
print(a4)
print('-' * 20)
print(b4)

[ 1.  5.  8.  9. 10.]
--------------------
[[-0.66280568 -0.47096807  0.22561768 -1.04617192  0.7383947  -1.03382219
   0.35677394 -0.21659241 -0.70515617 -0.30316389]
 [ 0.94634794  1.08653257  0.5871669  -0.08584565 -0.4219474   0.45693989
  -0.45819309 -0.86610361 -0.90128871 -1.36280905]
 [-0.79376331  0.04986632 -0.07642652  0.53623186  0.81505118  0.73838202
  -0.2489301  -0.28261793  0.79485771 -0.87212444]
 [-0.12152128 -1.26836659 -0.92585965 -1.20309212  0.96513725  1.22387413
  -0.11198889 -1.17087882  1.00641888 -0.22424133]
 [-0.29038945  0.20921193  1.47712692  0.30394688 -1.07743073 -0.51711237
   1.35619319  1.57105273  1.12669418 -0.08767327]]


In [11]:
# pandas로 불러오기 가능
import pandas as pd
df = pd.read_csv('save_data/b_txt.csv', header=None)
df

0         1         2         3         4         5         6  \
0 -0.662806 -0.470968  0.225618 -1.046172  0.738395 -1.033822  0.356774   
1  0.946348  1.086533  0.587167 -0.085846 -0.421947  0.456940 -0.458193   
2 -0.793763  0.049866 -0.076427  0.536232  0.815051  0.738382 -0.248930   
3 -0.121521 -1.268367 -0.925860 -1.203092  0.965137  1.223874 -0.111989   
4 -0.290389  0.209212  1.477127  0.303947 -1.077431 -0.517112  1.356193   

          7         8         9  
0 -0.216592 -0.705156 -0.303164  
1 -0.866104 -0.901289 -1.362809  
2 -0.282618  0.794858 -0.872124  
3 -1.170879  1.006419 -0.224241  
4  1.571053  1.126694 -0.087673